# -*- coding: utf-8 -*-
"""Health Premium

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EzApQajdc9Ug0_6t0ez2mTOdCV21LcxK
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

data = pd.read_csv('/content/Health_insurance.csv')
data.head()

data.isnull().sum()

data.duplicated().sum()

data.shape

data.info()

import plotly.express as px
data = data
figure = px.histogram(data, x = 'sex', color = 'smoker', title = 'Sex vs Smoker')
figure.show()

data["sex"] = data["sex"].map({"female": 0, "male": 1})
data["smoker"] = data["smoker"].map({"no": 0, "yes": 1})
print(data.head())

pie = data['region'].value_counts()
regions = pie.index
population = pie.values
figure = px.pie(data, values = population, names = regions, hole = 0.2)
figure.show()

data = pd.get_dummies(data, columns=['region'], drop_first=True)
print(data.corr())

x = np.array(data[["age", "sex", "bmi", "smoker"]])
y = np.array(data["charges"])

from sklearn.model_selection import train_test_split
xtrain, xtest, ytrain, ytest = train_test_split(x, y, test_size=0.2, random_state=42)

from sklearn.ensemble import RandomForestRegressor
forest = RandomForestRegressor()
forest.fit(xtrain, ytrain)

ypred = forest.predict(xtest)
data = pd.DataFrame(data={"Predicted Premium Amount": ypred})
print(data.head())

bar = px.bar(data, x =regions, y = population, title = 'Region vs Population', color = regions, text_auto = True)
bar.show()

line = px.line(data, x =regions, y = population, title = 'Region vs Population', color = regions, markers = True)
line.show()

"""## Distribution of charges (Histogram)"""

plt.figure(figsize=(10, 6))
sns.histplot(y, kde=True, color='teal')
plt.title('1. Distribution of Insurance Expenses')
plt.xlabel('Expenses')
plt.ylabel('Frequency')
plt.show()

"""## BMI Vs charges (Scatter Plot)"""

plot_data_for_bmi_charges = pd.DataFrame({'bmi': x[:, 2], 'charges': y})

plt.figure(figsize=(10, 6))
sns.scatterplot(data=plot_data_for_bmi_charges, x='bmi', y='charges', alpha=0.5) # Changed 'expenses' to 'charges' and 'data' to plot_data_for_bmi_charges
plt.title('2. BMI vs Insurance Expenses')
plt.xlabel('BMI')
plt.ylabel('Expenses') # Keep as 'Expenses' for presentation, though the data column is 'charges'
plt.show()

"""## Smoker Vs Charged"""

plot_data_for_smoker_charges = pd.DataFrame({'smoker': x[:, 3], 'charges': y})

plt.figure(figsize=(10, 6))
sns.boxplot(data=plot_data_for_smoker_charges, x='smoker', y='charges', palette='Set2')
plt.title('3. Insurance Expenses: Smoker vs Non-Smoker')
plt.xlabel('Smoker')
plt.ylabel('Expenses')
plt.show()

"""## Age Vs Charged"""

plot_data_for_age_charges = pd.DataFrame({'age': x[:, 0], 'smoker': x[:, 3], 'charges': y})

plt.figure(figsize=(10, 6))
# Using hue to show the impact of smoking status on age/cost
sns.scatterplot(data=plot_data_for_age_charges, x='age', y='charges', hue='smoker', alpha=0.6)
plt.title('4. Age vs Insurance Expenses')
plt.xlabel('Age')
plt.ylabel('Expenses')
plt.savefig('plot_4_age_vs_expenses.png')

"""## Region Wise Analysis"""

plt.figure(figsize=(10, 6))
sns.barplot(x=regions, y=population, palette='viridis')
plt.title('5. Distribution of Samples by Region')
plt.xlabel('Region')
plt.ylabel('Count')
plt.show()

"""## Correlation Heatmap"""

plt.figure(figsize=(10, 8))

# Using the data DataFrame which contains the necessary numerical columns
# for age, sex, bmi, smoker, and charges, and the one-hot encoded regions.
corr = data.corr()

sns.heatmap(corr, annot=True, cmap='coolwarm', fmt=".2f")
plt.title('6. Correlation Heatmap')
plt.show()

# Reload the original data as the 'data' variable has been transformed
original_data = pd.read_csv('/content/Health_insurance.csv')

plt.figure(figsize=(10,6))
sns.countplot(data=original_data, x='region', hue='smoker', palette='pastel')
plt.title('7. Smoker Distribution by Region')
plt.xlabel('Region')
plt.ylabel('Count')
plt.show()

"""## BMI Distribution By Region"""

plt.figure(figsize=(10,8))
sns.boxplot(x='region', y='bmi', data=original_data, palette='pastel')
plt.title ('8. BMI Distribution by Region')
plt.xlabel('Region')
plt.ylabel('BMI')
plt.show()

"""## Region Vs Children Plot"""

plt.figure(figsize=(10,8))
sns.countplot(data=original_data, x='region', hue='children', palette='tab10')
plt.title('9. Region Vs Children')
plt.xlabel('Region')
plt.ylabel('Count of Individuals')
plt.show()